version: '3.7'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
        - local_network
  userservice:
    container_name: userservice
    image: userservice
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
        - local_network

  reservationservice:
    container_name: reservationservice
    image: reservationservice
    build:
      context: .
      dockerfile: ./ReservationService/Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - db
    networks:
        - local_network
  db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Your_password123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: xml_volume
        target: /var/opt/mssql
    networks:
        - local_network
networks:
  local_network:
    driver: bridge
volumes:
  xml_volume: